feat: almost have this devcontainer working

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,64 +1,114 @@
+# syntax=docker/dockerfile:1
 # for format details, see https://docs.docker.com/engine/reference/builder/
 
-ARG BASE_VARIANT="2-jammy"
+ARG VARIANT="noble"
 
-FROM mcr.microsoft.com/devcontainers/base:${BASE_VARIANT}
+ARG LANG="en_US.UTF-8"
+ARG HOSTNAME="scala-container"
+ARG USERNAME="vscode"
+ARG USER_UID="1000"
+ARG USER_GID="1000"
+ARG USER_GECOS="Interactive User"
+ARG COURSIER_CACHE="/root/coursier-cache"
 
-ARG USERNAME "vscode"
-RUN <<EOF
+# Official Docker "BuildPack" image (Ubuntu)
+FROM buildpack-deps:${VARIANT}-curl AS base
+
+ENV JAVA_JDK_VERSION="17"
+ENV ALMOND_VERSION="0.14.1"
+ENV SCALA_VERSION="2.13.1"
+ENV COURSIER_INSTALL_DIR="/usr/local/bin"
+ENV UV_INSTALL_DIR="/usr/local/bin"
+
+ENV SHELL="/bin/bash"
+SHELL [ "/bin/bash", "-c" ]
+
+ARG VARIANT
+RUN if [ "$VARIANT" = "noble" ]; then \
+        if id "ubuntu" &>/dev/null; then \
+            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \
+        else \
+            echo "User 'ubuntu' does not exist for $VARIANT"; \
+        fi; \
+    fi
+
+# Performm basic OS configuration for interactive use
+ARG LANG
+ARG HOSTNAME
+RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
+  --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib \
+  <<EOF
+echo $HOSTNAME > /etc/hostname
+hostname $HOSTNAME
 export DEBIAN_FRONTEND=noninteractive
 apt-get update
-# optional: restore 'man'
-yes | unminimize 2>&1
 apt-get install -y --no-install-recommends \
-  sudo fish xonsh unzip zip curl wget openjdk-18-jdk
+  sudo man-db manpages locales \
+  unzip zip gzip curl apt-utils openssh-client gnupg2 ca-certificates
+locale-gen "$LANG"
+apt-get dist-clean -y
+EOF
+
+FROM base AS base-jdk
+WORKDIR /root
+COPY install-jdk.sh /root/
+RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
+  --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib \
+  bash ./install-jdk.sh
+
+ARG COURSIER_CACHE
+FROM base-jdk AS base-scala
+WORKDIR /root
+COPY install-scala.sh /root/
+COPY load-spinal.sc /usr/local/lib/
+RUN --mount=type=cache,target=${COURSIER_CACHE},sharing=locked,id=coursier-cache \
+  bash ./install-scala.sh
+
+FROM base-scala AS base-python
+WORKDIR /root
+COPY install-python.sh /root/
+RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
+  --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib \
+  bash ./install-python.sh
+
+FROM base-python AS base-jupyter
+WORKDIR /root
+COPY install-jupyter.sh /root/
+RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
+  --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib \
+  bash ./install-jupyter.sh
+
+# update packages and dist-clean
+FROM base-jupyter AS final
+RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
+  --mount=type=cache,target=/var/lib/apt,sharing=locked,id=apt-lib \
+ <<EOF
 apt-get update
-apt-get upgrade -y
-# optional: provide sudo access
+apt-get -y autoremove
+apt-get -y dist-upgrade
+apt-get -y dist-clean
+EOF
+
+# Add the default non-root user
+ARG USERNAME
+ARG USER_UID
+ARG USER_GID
+ARG USER_GECOS
+RUN <<EOF
+groupadd --gid $USER_GID $USERNAME
+useradd -s /bin/bash --uid $USER_UID --gid $USER_GID --comment "$USER_GECOS" -m $USERNAME
 echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME
 chmod 0440 /etc/sudoers.d/$USERNAME
-# These may not be needed but they're here "just in case".
-apt-get autoremove -y
-apt-get clean -y
-apt-get purge -y
-rm -rf /tmp/scripts
-apt-get update
 EOF
-
-ENV SHELL=/bin/bash DOCKER_BUILDKIT=1
-
-ARG USERNAME
-COPY load-spinal.sc /home/${USERNAME}/
-# change user, not root anymore.
-
+# Change to user home
 ARG USERNAME
 WORKDIR /home/${USERNAME}/
-
+# change user, not root anymore.
 ARG USERNAME
 USER ${USERNAME}
+COPY load-spinal.sc .
 
-RUN <<EOF
-curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux-mostly-static.gz" | gzip -d > /tmp/cs
-chmod +x /tmp/cs
-/tmp/cs setup -v -y
-rm -rf /tmp/cs
-cd $HOME
-. ./.profile
-coursier install almond mill
-pipx install --force --include-deps notebook jupyter-core jupyter-client jupyter-server
-ipython kernel install --user
-almond --install -f
-jupyter kernelspec list > kernelspec.txt
-jupyter --paths
-jupyter --paths > jupyter-paths.txt
-. ./.profile
-git clone --depth 1 https://github.com/SpinalHDL/SpinalTemplateSbt.git SpinalTemplateSbt
-cd SpinalTemplateSbt
-rm -rf .git
-EOF
-
-LABEL description="VSCode/VSCodium dev container for Jupyter + Scala + SpinalHDL" \
+LABEL description="Development container for Scala + SpinalHDL + Jupyter" \
       author="rjstoneus@gmail.com" \
       maintainer="rjstoneus@gmail.com" \
-      version="0.0.4"
-
+      version="0.3.0"
